// Generates the `@cipherstash/protect-ffi/wasm-inline` entry from wasm-pack output.
// Required because `--target bundler` emits `import * as wasm from "./*.wasm"`,
// which fails in runtimes that don't auto-bundle sibling `.wasm` assets
// (Supabase Edge, Cloudflare Workers without binding declarations, etc.).
//
// Ported from cipherstash-suite/packages/stack-auth/node/scripts/inline-wasm.mjs.

import { readFile, rm, writeFile } from 'node:fs/promises'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const here = dirname(fileURLToPath(import.meta.url))
const wasmDir = resolve(here, '..', 'dist', 'wasm')

const wasmBytes = await readFile(resolve(wasmDir, 'protect_ffi_bg.wasm'))
const base64 = wasmBytes.toString('base64')

// Reuse the export list wasm-pack itself wrote into the bundler stub —
// avoids drifting if new wasm-bindgen exports are added or renamed.
const bundlerStub = await readFile(resolve(wasmDir, 'protect_ffi.js'), 'utf-8')
const exportMatch = bundlerStub.match(
  /export\s*\{([\s\S]*?)\}\s*from\s*"\.\/protect_ffi_bg\.js";/,
)
if (!exportMatch) {
  throw new Error(
    'inline-wasm: could not parse export list from protect_ffi.js',
  )
}
const exportList = exportMatch[1].trim()
const errorHelperExport =
  'export { PROTECT_ERROR_CODES, isProtectErrorCode } from "./errors.js";'

// wasm-bindgen owns the main stub and cannot re-export arbitrary JavaScript
// values from a TypeScript custom section. Add the runtime half of the error
// helper API after wasm-pack has generated the file. `errors.js` is compiled
// as ESM from the same `src/errors.ts` the native entry uses, so edge runtimes
// do not have to load CommonJS and the code list still has one source.
await writeFile(
  resolve(wasmDir, 'protect_ffi.js'),
  `${bundlerStub.trimEnd()}\n${errorHelperExport}\n`,
)

// NOTE: we deliberately omit wasm-bindgen's `@ts-self-types` directive here.
// Supabase Edge's module-graph resolver treats it as a hard external import
// and rejects the inline file with "Module not found protect_ffi.d.ts" even
// when the file exists on disk, because the import map only knows about
// this inline entry. Types are still consumable by Node/bundler builds via
// the package.json `exports` map pointing at protect_ffi.d.ts directly.
const shim = `// Generated by scripts/inline-wasm.mjs — do not edit.

import * as bgImports from "./protect_ffi_bg.js";

const WASM_BYTES_B64 = "${base64}";
const wasmBytes = Uint8Array.from(atob(WASM_BYTES_B64), (c) => c.charCodeAt(0));

const { instance } = await WebAssembly.instantiate(wasmBytes, {
  "./protect_ffi_bg.js": bgImports,
});
bgImports.__wbg_set_wasm(instance.exports);
instance.exports.__wbindgen_start();

export {
${exportList}
} from "./protect_ffi_bg.js";

${errorHelperExport}
`

const outPath = resolve(wasmDir, 'protect_ffi_inline.js')
await writeFile(outPath, shim)

// wasm-pack `--target bundler` emits ESM (`import` / `export`) into
// `protect_ffi.js`, and the inline shim above is ESM too. The root
// `package.json` has no `"type": "module"`, so without a scoped marker
// Node would parse these as CJS and fail to load the `./wasm` and
// `./wasm-inline` subpath exports. Write a sibling `package.json` that
// scopes only `dist/wasm/**` as ESM; CJS semantics elsewhere are unchanged.
const pkgPath = resolve(wasmDir, 'package.json')
await writeFile(pkgPath, `${JSON.stringify({ type: 'module' }, null, 2)}\n`)

// wasm-pack writes its own `dist/wasm/.gitignore` containing `*`, on the
// assumption that everything it generates is disposable. Three files here are
// not: `protect_ffi.d.ts`, `protect_ffi_bg.wasm.d.ts` and `errors.d.ts` are
// tracked so `packages/stack`'s declaration build resolves
// `@cipherstash/protect-ffi/wasm-inline` without a Rust toolchain (see the
// repo root `.gitignore`).
//
// It has to be removed rather than negated around: the deepest `.gitignore`
// wins, so that `*` overrides every negation in the two files above it. The
// runtime output stays ignored by those parent rules regardless.
const wasmPackIgnore = resolve(wasmDir, '.gitignore')
await rm(wasmPackIgnore, { force: true })

console.log(
  `inline-wasm: wrote protect_ffi_inline.js (${wasmBytes.length} wasm bytes -> ${base64.length} b64 chars) and package.json (type=module); removed wasm-pack's .gitignore`,
)
