// @generated — vendored from eql-bindings bindings/v3 (encrypt-query-language).
// Do not hand-edit. Refresh with scripts/sync-eql-v3-types.sh.
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Identifier } from "./Identifier";
import type { OreBlock256 } from "./OreBlock256";
import type { SchemaVersion } from "./SchemaVersion";

/**
 * `eql_v3.query_bigint_ord_ore` — ordering domain query operand.
 *
 * Operators: `=` `<>` `<` `<=` `>` `>=`. Required keys: `v` `i` `ob`.
 */
export type BigintOrdOreQuery = { v: SchemaVersion, i: Identifier, ob: OreBlock256, };
