// @generated — vendored from eql-bindings bindings/v3 (encrypt-query-language).
// Do not hand-edit. Refresh with scripts/sync-eql-v3-types.sh.
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * mp_base85 source ciphertext — the `c` envelope key.
 *
 * Required by every v3 domain CHECK; present on every payload.
 */
export type Ciphertext = string;
