// @generated — vendored from eql-bindings bindings/v3 (encrypt-query-language).
// Do not hand-edit. Refresh with scripts/sync-eql-v3-types.sh.
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A SteVec entry's ciphertext — the sv-element `c` key: base85 of the raw
 * AEAD output only.
 *
 * NOT a self-describing record (contrast [`Ciphertext`]): the key material
 * lives once in the document's `h` ([`KeyHeader`]) and the AEAD nonce is
 * derived from the entry's selector (`hex_decode(s)[..12]`), so the
 * decryption unit is the entry — `h` + `s` + `c`.
 */
export type EntryCiphertext = string;
