// @generated — vendored from eql-bindings bindings/v3 (encrypt-query-language).
// Do not hand-edit. Refresh with scripts/sync-eql-v3-types.sh.
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * HMAC-SHA-256 equality term — the `hm` wire key. Backs the `_eq` domains
 * (`=`, `<>`). SQL-side constructor: `eql_v3_internal.hmac_256`.
 */
export type Hmac256 = string;
