// @generated — vendored from eql-bindings bindings/v3 (encrypt-query-language).
// Do not hand-edit. Refresh with scripts/sync-eql-v3-types.sh.
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Table + column identifier — wire shape `{"t": "...", "c": "..."}`.
 *
 * Shared by every payload.
 */
export type Identifier = { 
/**
 * Table name.
 */
t: string, 
/**
 * Column name.
 */
c: string, };
