// @generated — vendored from eql-bindings bindings/v3 (encrypt-query-language).
// Do not hand-edit. Refresh with scripts/sync-eql-v3-types.sh.
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The document key header — the `h` envelope key of a SteVec document.
 *
 * mp_base85-encoded key-retrieval material (IV, key tag, descriptor, keyset
 * id), stored **once** per document: every sv entry encrypts under the
 * document's single data key, and entry nonces are derived from the
 * entries' selectors, so nothing per-entry is repeated. Opaque to SQL — it
 * is carried and grafted (`->` merges it onto extracted entries via
 * `eql_v3.meta_data`), never parsed database-side.
 */
export type KeyHeader = string;
