// @generated — vendored from eql-bindings bindings/v3 (encrypt-query-language).
// Do not hand-edit. Refresh with scripts/sync-eql-v3-types.sh.
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Ciphertext } from "./Ciphertext";
import type { Hmac256 } from "./Hmac256";
import type { Identifier } from "./Identifier";
import type { SchemaVersion } from "./SchemaVersion";

/**
 * `public.eql_v3_numeric_eq` — equality domain.
 *
 * Operators: `=` `<>`. Required keys: `v` `i` `c` `hm`.
 */
export type NumericEq = { v: SchemaVersion, i: Identifier, c: Ciphertext, hm: Hmac256, };
