// @generated — vendored from eql-bindings bindings/v3 (encrypt-query-language).
// Do not hand-edit. Refresh with scripts/sync-eql-v3-types.sh.
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Identifier } from "./Identifier";
import type { OpeCllw } from "./OpeCllw";
import type { SchemaVersion } from "./SchemaVersion";

/**
 * `eql_v3.query_numeric_ord` — ordering domain query operand.
 *
 * Operators: `=` `<>` `<` `<=` `>` `>=`. Required keys: `v` `i` `op`.
 */
export type NumericOrdQuery = { v: SchemaVersion, i: Identifier, op: OpeCllw, };
