// @generated — vendored from eql-bindings bindings/v3 (encrypt-query-language).
// Do not hand-edit. Refresh with scripts/sync-eql-v3-types.sh.
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * CLLW-OPE order term — the `op` wire key. Backs the scalar `_ord` (the
 * default ordering domain), `_ord_ope`, and `text_search` domains, their
 * `query_` operands (`=` `<>` `<` `<=` `>` `>=`), and the ordered
 * (number/string) path entries of a SteVec document (the only per-entry
 * term — `hm` is retired; exact matching is the value-inclusive selector):
 * a hex-encoded CLLW OPE ciphertext, sortable via native bytea comparison
 * after hex-decode — unlike `ob` (block-ORE) it needs no custom comparator.
 * Extracted by `eql_v3.ord_term` (scalar domains and the
 * `public.eql_v3_json_entry` overload alike); SQL-side constructor:
 * `eql_v3_internal.ope_cllw`.
 */
export type OpeCllw = string;
