// @generated — vendored from eql-bindings bindings/v3 (encrypt-query-language).
// Do not hand-edit. Refresh with scripts/sync-eql-v3-types.sh.
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Block-ORE order term — the `ob` wire key. Backs the `_ord_ore` domains and
 * `text_search_ore` (`=` `<>` `<` `<=` `>` `>=`); ORE is lossless over the scalar's
 * domain, so it serves equality too. The block count is width-agnostic on the
 * wire (8 for the int scalars, 12 for timestamp, 14 for numeric) — the
 * array just carries more block strings. Extracted by `eql_v3.ord_term_ore`;
 * SQL-side constructor: `eql_v3_internal.ore_block_256`.
 */
export type OreBlock256 = Array<string>;
