// @generated — vendored from eql-bindings bindings/v3 (encrypt-query-language).
// Do not hand-edit. Refresh with scripts/sync-eql-v3-types.sh.
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The envelope version field (`v`) — always exactly [`EQL_SCHEMA_VERSION`]
 * on the wire.
 *
 * Deserialization rejects any other value: the Rust analogue of the domain
 * CHECK's `VALUE->>'v' = '3'`, so a wrong-version payload fails at the type
 * boundary instead of at INSERT. The inner value is private; the only
 * constructible instance is the current version.
 */
export type SchemaVersion = 3;
