// @generated — vendored from eql-bindings bindings/v3 (encrypt-query-language).
// Do not hand-edit. Refresh with scripts/sync-eql-v3-types.sh.
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A SteVec selector — the `s` wire key. Addresses a JSON path leaf within an
 * encrypted document (`public.eql_v3_json_search`); present on every entry and query element.
 */
export type Selector = string;
