// @generated — vendored from eql-bindings bindings/v3 (encrypt-query-language).
// Do not hand-edit. Refresh with scripts/sync-eql-v3-types.sh.
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OpeCllw } from "./OpeCllw";
import type { Selector } from "./Selector";

/**
 * One element of a SteVec containment needle: a selector plus — for ordered
 * path entries only — the `op` ordering term; value-selector and structural
 * entries are selector-only (matched on presence), and (per the SQL CHECK)
 * no element carries a ciphertext. Unknown fields are rejected so the Rust
 * parser and published JSON Schema enforce the same boundary as PostgreSQL.
 */
export type SteVecQueryEntry = { s: Selector, op?: OpeCllw, };
