// @generated — vendored from eql-bindings bindings/v3 (encrypt-query-language).
// Do not hand-edit. Refresh with scripts/sync-eql-v3-types.sh.
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Identifier } from "./Identifier";
import type { KeyHeader } from "./KeyHeader";
import type { SchemaVersion } from "./SchemaVersion";
import type { SteVecEntry } from "./SteVecEntry";
import type { SteVecForm } from "./SteVecForm";

/**
 * `public.eql_v3_json_search` — a SteVec encrypted-JSON document
 * (`{v, k, i, h, sv:[entry]}`, no root ciphertext — the root document
 * ciphertext lives on the root sv entry). Strict. `k` is the `"sv"` form
 * discriminator (see [`SteVecForm`]); `h` is the document [`KeyHeader`],
 * stored once for the whole document (every entry encrypts under the
 * document's single data key, with per-entry nonces derived from the
 * entries' selectors).
 */
export type SteVecDocument = { v: SchemaVersion, k: SteVecForm, i: Identifier, h: KeyHeader, sv: Array<SteVecEntry>, };
