// @generated — vendored from eql-bindings bindings/v3 (encrypt-query-language).
// Do not hand-edit. Refresh with scripts/sync-eql-v3-types.sh.
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EntryCiphertext } from "./EntryCiphertext";
import type { Identifier } from "./Identifier";
import type { KeyHeader } from "./KeyHeader";
import type { OpeCllw } from "./OpeCllw";
import type { SchemaVersion } from "./SchemaVersion";
import type { Selector } from "./Selector";

/**
 * `public.eql_v3_json_entry` — one sv element (returned by `->`). Carries a
 * selector `s`, raw AEAD ciphertext `c` (see [`EntryCiphertext`] — the
 * decryption unit is `h` + `s` + `c`, with the document `h` grafted onto
 * extracted entries by `->`), an optional array-membership marker `a`
 * (emitted only when true), and — for ordered (number/string) path entries
 * only — the `op` ordering term. Value entries (value-inclusive selectors)
 * and non-orderable path entries are term-less: exact matching is selector
 * presence, so no per-entry equality term exists (`hm` is retired). The
 * optional `i`/`v`/`h` fields model metadata grafted onto an entry returned by
 * `->`; naming them explicitly keeps unknown keys rejectable.
 */
export type SteVecEntry = { s: Selector, c: EntryCiphertext, a?: boolean | null, op?: OpeCllw, i?: Identifier, v?: SchemaVersion, h?: KeyHeader, };
