// @generated — vendored from eql-bindings bindings/v3 (encrypt-query-language).
// Do not hand-edit. Refresh with scripts/sync-eql-v3-types.sh.
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SteVecQueryEntry } from "./SteVecQueryEntry";

/**
 * `eql_v3.query_json` — a containment needle (`{sv:[query-entry]}`). Strict.
 */
export type SteVecQuery = { sv: Array<SteVecQueryEntry>, };
