// @generated — vendored from eql-bindings bindings/v3 (encrypt-query-language).
// Do not hand-edit. Refresh with scripts/sync-eql-v3-types.sh.
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The `k` envelope key — the EQL payload **form discriminator**, always the
 * literal `"sv"` for an encrypted-JSONB document.
 *
 * `k` distinguishes the payload forms in the canonical wire contract (`"ct"` =
 * scalar ciphertext, `"sv"` = STE-vec). `eql_v3` itself does not consume `k`
 * (the typed domain + the structural `c`-vs-`sv` shape already discriminate,
 * and no `eql_v3` SQL reads it), but the canonical `SteVecPayload`
 * (`eql-payload-v2.3.schema.json`, `required: [v,k,i,sv]`) mandates it and
 * cipherstash-client emits it on every SteVec document — so the strict document
 * struct must model it or it rejects the real wire.
 *
 * Pinned exactly like [`SchemaVersion`] pins `v`: deserialization rejects any
 * value other than `"sv"`, so a scalar (`k:"ct"`) payload cannot be read back
 * as a document. The inner value is private; the only constructible instance is
 * [`SteVecForm::SV`].
 */
export type SteVecForm = "sv";
