// @generated — vendored from eql-bindings bindings/v3 (encrypt-query-language).
// Do not hand-edit. Refresh with scripts/sync-eql-v3-types.sh.
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BloomFilter } from "./BloomFilter";
import type { Identifier } from "./Identifier";
import type { SchemaVersion } from "./SchemaVersion";

/**
 * `eql_v3.query_text_match` — match domain query operand.
 *
 * Operators: `@@`. Required keys: `v` `i` `bf`.
 */
export type TextMatchQuery = { v: SchemaVersion, i: Identifier, bf: BloomFilter, };
