// @generated — vendored from eql-bindings bindings/v3 (encrypt-query-language).
// Do not hand-edit. Refresh with scripts/sync-eql-v3-types.sh.
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BloomFilter } from "./BloomFilter";
import type { Hmac256 } from "./Hmac256";
import type { Identifier } from "./Identifier";
import type { OpeCllw } from "./OpeCllw";
import type { SchemaVersion } from "./SchemaVersion";

/**
 * `eql_v3.query_text_search` — search domain query operand.
 *
 * Operators: `=` `<>` `<` `<=` `>` `>=` `@@`. Required keys: `v` `i` `hm` `op` `bf`.
 */
export type TextSearchQuery = { v: SchemaVersion, i: Identifier, hm: Hmac256, op: OpeCllw, bf: BloomFilter, };
