// ⚠️  GENERATED FILE - DO NOT EDIT
// This file is automatically generated by 'prisma-next contract emit'.
// To regenerate, run: prisma-next contract emit
import type { CodecTypes as CipherstashTypes } from '@cipherstash/stack-prisma/codec-types';
import type { QueryOperationTypes as CipherstashQueryOperationTypes } from '@cipherstash/stack-prisma/operation-types';
import type {
  EncryptedBigInt,
  EncryptedBoolean,
  EncryptedDate,
  EncryptedJson,
  EncryptedNumber,
  EncryptedString,
} from '@cipherstash/stack-prisma/runtime';
import type { QueryOperationTypes as PgAdapterQueryOps } from '@prisma/orm-postgres/adapter/operation-types';
import type {
  Bit,
  Char,
  CodecTypes as PgTypes,
  Interval,
  JsonValue,
  Numeric,
  Time,
  Timestamp,
  Timestamptz,
  Timetz,
  VarBit,
  Varchar,
} from '@prisma/orm-postgres/target/codec-types';

import type {
  ContractWithTypeMaps,
  TypeMaps as TypeMapsType,
} from '@prisma/orm-postgres/family-contract/types';
import type {
  Contract as ContractType,
  ExecutionHashBase,
  NamespaceId,
  ProfileHashBase,
  StorageHashBase,
} from '@prisma/orm-postgres/contract/types';

export type StorageHash =
  StorageHashBase<'f1cd58a4c67d07d7c45d05b6d11a5629e063848d9597a17af2311542622cd8d7'>;
export type ExecutionHash = ExecutionHashBase<string>;
export type ProfileHash =
  ProfileHashBase<'3916f444a8a17ad749191acf9e08dad97d1a327b88c2f1d45d12f240296aa8b2'>;

export type CodecTypes = PgTypes & CipherstashTypes;
export type LaneCodecTypes = CodecTypes;
export type QueryOperationTypes = PgAdapterQueryOps<CodecTypes> &
  CipherstashQueryOperationTypes<CodecTypes>;
type DefaultLiteralValue<CodecId extends string, Encoded> = CodecId extends keyof CodecTypes
  ? Encoded extends CodecTypes[CodecId]['json']
    ? Encoded
    : CodecTypes[CodecId]['json']
  : Encoded;

export type FieldOutputTypes = {
  readonly public: {
    readonly User: {
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly email: EncryptedString;
      readonly salary: EncryptedNumber;
      readonly accountId: EncryptedBigInt;
      readonly birthday: EncryptedDate;
      readonly emailVerified: EncryptedBoolean;
      readonly preferences: EncryptedJson;
    };
  };
};
export type FieldInputTypes = {
  readonly public: {
    readonly User: {
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly email: CodecTypes['cipherstash/eql-v3/eql_v3_text_search@1']['input'];
      readonly salary: CodecTypes['cipherstash/eql-v3/eql_v3_double_ord@1']['input'];
      readonly accountId: CodecTypes['cipherstash/eql-v3/eql_v3_bigint_ord@1']['input'];
      readonly birthday: CodecTypes['cipherstash/eql-v3/eql_v3_date_ord@1']['input'];
      readonly emailVerified: CodecTypes['cipherstash/eql-v3/eql_v3_boolean@1']['input'];
      readonly preferences: CodecTypes['cipherstash/eql-v3/eql_v3_json_search@1']['input'];
    };
  };
};
export type StorageColumnTypes = {
  readonly public: {
    readonly users: {
      readonly accountid: EncryptedBigInt;
      readonly birthday: EncryptedDate;
      readonly email: EncryptedString;
      readonly emailverified: EncryptedBoolean;
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly preferences: EncryptedJson;
      readonly salary: EncryptedNumber;
    };
  };
};
export type StorageColumnInputTypes = {
  readonly public: {
    readonly users: {
      readonly accountid: CodecTypes['cipherstash/eql-v3/eql_v3_bigint_ord@1']['input'];
      readonly birthday: CodecTypes['cipherstash/eql-v3/eql_v3_date_ord@1']['input'];
      readonly email: CodecTypes['cipherstash/eql-v3/eql_v3_text_search@1']['input'];
      readonly emailverified: CodecTypes['cipherstash/eql-v3/eql_v3_boolean@1']['input'];
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly preferences: CodecTypes['cipherstash/eql-v3/eql_v3_json_search@1']['input'];
      readonly salary: CodecTypes['cipherstash/eql-v3/eql_v3_double_ord@1']['input'];
    };
  };
};
export type TypeMaps = TypeMapsType<
  CodecTypes,
  QueryOperationTypes,
  FieldOutputTypes,
  FieldInputTypes,
  StorageColumnTypes,
  StorageColumnInputTypes
>;

type ContractBase = Omit<
  ContractType<{
    readonly namespaces: {
      readonly public: {
        readonly id: 'public';
        readonly kind: 'postgres-schema';
        readonly entries: {
          readonly table: {
            readonly users: {
              columns: {
                readonly id: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly email: {
                  readonly nativeType: 'public.eql_v3_text_search';
                  readonly codecId: 'cipherstash/eql-v3/eql_v3_text_search@1';
                  readonly nullable: false;
                  readonly typeParams: {
                    readonly castAs: 'string';
                    readonly capabilities: {
                      readonly equality: true;
                      readonly orderAndRange: true;
                      readonly freeTextSearch: true;
                    };
                  };
                };
                readonly salary: {
                  readonly nativeType: 'public.eql_v3_double_ord';
                  readonly codecId: 'cipherstash/eql-v3/eql_v3_double_ord@1';
                  readonly nullable: false;
                  readonly typeParams: {
                    readonly castAs: 'number';
                    readonly capabilities: {
                      readonly equality: true;
                      readonly orderAndRange: true;
                      readonly freeTextSearch: false;
                    };
                  };
                };
                readonly accountid: {
                  readonly nativeType: 'public.eql_v3_bigint_ord';
                  readonly codecId: 'cipherstash/eql-v3/eql_v3_bigint_ord@1';
                  readonly nullable: false;
                  readonly typeParams: {
                    readonly castAs: 'bigint';
                    readonly capabilities: {
                      readonly equality: true;
                      readonly orderAndRange: true;
                      readonly freeTextSearch: false;
                    };
                  };
                };
                readonly birthday: {
                  readonly nativeType: 'public.eql_v3_date_ord';
                  readonly codecId: 'cipherstash/eql-v3/eql_v3_date_ord@1';
                  readonly nullable: false;
                  readonly typeParams: {
                    readonly castAs: 'date';
                    readonly capabilities: {
                      readonly equality: true;
                      readonly orderAndRange: true;
                      readonly freeTextSearch: false;
                    };
                  };
                };
                readonly emailverified: {
                  readonly nativeType: 'public.eql_v3_boolean';
                  readonly codecId: 'cipherstash/eql-v3/eql_v3_boolean@1';
                  readonly nullable: false;
                  readonly typeParams: {
                    readonly castAs: 'boolean';
                    readonly capabilities: {
                      readonly equality: false;
                      readonly orderAndRange: false;
                      readonly freeTextSearch: false;
                    };
                  };
                };
                readonly preferences: {
                  readonly nativeType: 'public.eql_v3_json_search';
                  readonly codecId: 'cipherstash/eql-v3/eql_v3_json_search@1';
                  readonly nullable: false;
                  readonly typeParams: {
                    readonly castAs: 'json';
                    readonly capabilities: {
                      readonly equality: false;
                      readonly orderAndRange: false;
                      readonly freeTextSearch: false;
                      readonly searchableJson: true;
                    };
                  };
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [];
              indexes: readonly [];
              foreignKeys: readonly [];
            };
          };
        };
      };
    };
    readonly storageHash: StorageHash;
  }>,
  'roots' | 'domain'
> & {
  readonly target: 'postgres';
  readonly targetFamily: 'sql';
  readonly roots: {
    readonly users: { readonly namespace: 'public' & NamespaceId; readonly model: 'User' };
  };
  readonly domain: {
    readonly namespaces: {
      readonly public: {
        readonly models: {
          readonly User: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly email: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'cipherstash/eql-v3/eql_v3_text_search@1';
                  readonly typeParams: {
                    readonly castAs: 'string';
                    readonly capabilities: {
                      readonly equality: true;
                      readonly orderAndRange: true;
                      readonly freeTextSearch: true;
                    };
                  };
                };
              };
              readonly salary: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'cipherstash/eql-v3/eql_v3_double_ord@1';
                  readonly typeParams: {
                    readonly castAs: 'number';
                    readonly capabilities: {
                      readonly equality: true;
                      readonly orderAndRange: true;
                      readonly freeTextSearch: false;
                    };
                  };
                };
              };
              readonly accountId: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'cipherstash/eql-v3/eql_v3_bigint_ord@1';
                  readonly typeParams: {
                    readonly castAs: 'bigint';
                    readonly capabilities: {
                      readonly equality: true;
                      readonly orderAndRange: true;
                      readonly freeTextSearch: false;
                    };
                  };
                };
              };
              readonly birthday: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'cipherstash/eql-v3/eql_v3_date_ord@1';
                  readonly typeParams: {
                    readonly castAs: 'date';
                    readonly capabilities: {
                      readonly equality: true;
                      readonly orderAndRange: true;
                      readonly freeTextSearch: false;
                    };
                  };
                };
              };
              readonly emailVerified: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'cipherstash/eql-v3/eql_v3_boolean@1';
                  readonly typeParams: {
                    readonly castAs: 'boolean';
                    readonly capabilities: {
                      readonly equality: false;
                      readonly orderAndRange: false;
                      readonly freeTextSearch: false;
                    };
                  };
                };
              };
              readonly preferences: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'cipherstash/eql-v3/eql_v3_json_search@1';
                  readonly typeParams: {
                    readonly castAs: 'json';
                    readonly capabilities: {
                      readonly equality: false;
                      readonly orderAndRange: false;
                      readonly freeTextSearch: false;
                      readonly searchableJson: true;
                    };
                  };
                };
              };
            };
            readonly relations: Record<string, never>;
            readonly storage: {
              readonly table: 'users';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly email: { readonly column: 'email' };
                readonly salary: { readonly column: 'salary' };
                readonly accountId: { readonly column: 'accountid' };
                readonly birthday: { readonly column: 'birthday' };
                readonly emailVerified: { readonly column: 'emailverified' };
                readonly preferences: { readonly column: 'preferences' };
              };
            };
          };
        };
      };
    };
  };
  readonly capabilities: {
    readonly postgres: {
      readonly distinctOn: true;
      readonly jsonAgg: true;
      readonly lateral: true;
      readonly limit: true;
      readonly orderBy: true;
      readonly returning: true;
    };
    readonly sql: {
      readonly defaultInInsert: true;
      readonly enums: true;
      readonly lateral: true;
      readonly returning: true;
      readonly scalarList: true;
    };
  };
  readonly extensions: {
    readonly cipherstash: {
      readonly familyId: 'sql';
      readonly id: 'cipherstash';
      readonly kind: 'extension';
      readonly targetId: 'postgres';
      readonly types: {
        readonly codecTypes: {
          readonly import: {
            readonly alias: 'CipherstashTypes';
            readonly named: 'CodecTypes';
            readonly package: '@cipherstash/stack-prisma/codec-types';
          };
          readonly typeImports: readonly [
            {
              readonly alias: 'EncryptedString';
              readonly named: 'EncryptedString';
              readonly package: '@cipherstash/stack-prisma/runtime';
            },
            {
              readonly alias: 'EncryptedBigInt';
              readonly named: 'EncryptedBigInt';
              readonly package: '@cipherstash/stack-prisma/runtime';
            },
            {
              readonly alias: 'EncryptedDate';
              readonly named: 'EncryptedDate';
              readonly package: '@cipherstash/stack-prisma/runtime';
            },
            {
              readonly alias: 'EncryptedBoolean';
              readonly named: 'EncryptedBoolean';
              readonly package: '@cipherstash/stack-prisma/runtime';
            },
            {
              readonly alias: 'EncryptedJson';
              readonly named: 'EncryptedJson';
              readonly package: '@cipherstash/stack-prisma/runtime';
            },
            {
              readonly alias: 'EncryptedNumber';
              readonly named: 'EncryptedNumber';
              readonly package: '@cipherstash/stack-prisma/runtime';
            },
          ];
        };
        readonly queryOperationTypes: {
          readonly import: {
            readonly alias: 'CipherstashQueryOperationTypes';
            readonly named: 'QueryOperationTypes';
            readonly package: '@cipherstash/stack-prisma/operation-types';
          };
        };
        readonly storage: readonly [
          {
            readonly familyId: 'sql';
            readonly nativeType: 'public.eql_v3_integer';
            readonly targetId: 'postgres';
            readonly typeId: 'cipherstash/eql-v3/eql_v3_integer@1';
          },
          {
            readonly familyId: 'sql';
            readonly nativeType: 'public.eql_v3_integer_eq';
            readonly targetId: 'postgres';
            readonly typeId: 'cipherstash/eql-v3/eql_v3_integer_eq@1';
          },
          {
            readonly familyId: 'sql';
            readonly nativeType: 'public.eql_v3_integer_ord_ore';
            readonly targetId: 'postgres';
            readonly typeId: 'cipherstash/eql-v3/eql_v3_integer_ord_ore@1';
          },
          {
            readonly familyId: 'sql';
            readonly nativeType: 'public.eql_v3_integer_ord';
            readonly targetId: 'postgres';
            readonly typeId: 'cipherstash/eql-v3/eql_v3_integer_ord@1';
          },
          {
            readonly familyId: 'sql';
            readonly nativeType: 'public.eql_v3_smallint';
            readonly targetId: 'postgres';
            readonly typeId: 'cipherstash/eql-v3/eql_v3_smallint@1';
          },
          {
            readonly familyId: 'sql';
            readonly nativeType: 'public.eql_v3_smallint_eq';
            readonly targetId: 'postgres';
            readonly typeId: 'cipherstash/eql-v3/eql_v3_smallint_eq@1';
          },
          {
            readonly familyId: 'sql';
            readonly nativeType: 'public.eql_v3_smallint_ord_ore';
            readonly targetId: 'postgres';
            readonly typeId: 'cipherstash/eql-v3/eql_v3_smallint_ord_ore@1';
          },
          {
            readonly familyId: 'sql';
            readonly nativeType: 'public.eql_v3_smallint_ord';
            readonly targetId: 'postgres';
            readonly typeId: 'cipherstash/eql-v3/eql_v3_smallint_ord@1';
          },
          {
            readonly familyId: 'sql';
            readonly nativeType: 'public.eql_v3_bigint';
            readonly targetId: 'postgres';
            readonly typeId: 'cipherstash/eql-v3/eql_v3_bigint@1';
          },
          {
            readonly familyId: 'sql';
            readonly nativeType: 'public.eql_v3_bigint_eq';
            readonly targetId: 'postgres';
            readonly typeId: 'cipherstash/eql-v3/eql_v3_bigint_eq@1';
          },
          {
            readonly familyId: 'sql';
            readonly nativeType: 'public.eql_v3_bigint_ord_ore';
            readonly targetId: 'postgres';
            readonly typeId: 'cipherstash/eql-v3/eql_v3_bigint_ord_ore@1';
          },
          {
            readonly familyId: 'sql';
            readonly nativeType: 'public.eql_v3_bigint_ord';
            readonly targetId: 'postgres';
            readonly typeId: 'cipherstash/eql-v3/eql_v3_bigint_ord@1';
          },
          {
            readonly familyId: 'sql';
            readonly nativeType: 'public.eql_v3_date';
            readonly targetId: 'postgres';
            readonly typeId: 'cipherstash/eql-v3/eql_v3_date@1';
          },
          {
            readonly familyId: 'sql';
            readonly nativeType: 'public.eql_v3_date_eq';
            readonly targetId: 'postgres';
            readonly typeId: 'cipherstash/eql-v3/eql_v3_date_eq@1';
          },
          {
            readonly familyId: 'sql';
            readonly nativeType: 'public.eql_v3_date_ord_ore';
            readonly targetId: 'postgres';
            readonly typeId: 'cipherstash/eql-v3/eql_v3_date_ord_ore@1';
          },
          {
            readonly familyId: 'sql';
            readonly nativeType: 'public.eql_v3_date_ord';
            readonly targetId: 'postgres';
            readonly typeId: 'cipherstash/eql-v3/eql_v3_date_ord@1';
          },
          {
            readonly familyId: 'sql';
            readonly nativeType: 'public.eql_v3_timestamp';
            readonly targetId: 'postgres';
            readonly typeId: 'cipherstash/eql-v3/eql_v3_timestamp@1';
          },
          {
            readonly familyId: 'sql';
            readonly nativeType: 'public.eql_v3_timestamp_eq';
            readonly targetId: 'postgres';
            readonly typeId: 'cipherstash/eql-v3/eql_v3_timestamp_eq@1';
          },
          {
            readonly familyId: 'sql';
            readonly nativeType: 'public.eql_v3_timestamp_ord_ore';
            readonly targetId: 'postgres';
            readonly typeId: 'cipherstash/eql-v3/eql_v3_timestamp_ord_ore@1';
          },
          {
            readonly familyId: 'sql';
            readonly nativeType: 'public.eql_v3_timestamp_ord';
            readonly targetId: 'postgres';
            readonly typeId: 'cipherstash/eql-v3/eql_v3_timestamp_ord@1';
          },
          {
            readonly familyId: 'sql';
            readonly nativeType: 'public.eql_v3_numeric';
            readonly targetId: 'postgres';
            readonly typeId: 'cipherstash/eql-v3/eql_v3_numeric@1';
          },
          {
            readonly familyId: 'sql';
            readonly nativeType: 'public.eql_v3_numeric_eq';
            readonly targetId: 'postgres';
            readonly typeId: 'cipherstash/eql-v3/eql_v3_numeric_eq@1';
          },
          {
            readonly familyId: 'sql';
            readonly nativeType: 'public.eql_v3_numeric_ord_ore';
            readonly targetId: 'postgres';
            readonly typeId: 'cipherstash/eql-v3/eql_v3_numeric_ord_ore@1';
          },
          {
            readonly familyId: 'sql';
            readonly nativeType: 'public.eql_v3_numeric_ord';
            readonly targetId: 'postgres';
            readonly typeId: 'cipherstash/eql-v3/eql_v3_numeric_ord@1';
          },
          {
            readonly familyId: 'sql';
            readonly nativeType: 'public.eql_v3_text';
            readonly targetId: 'postgres';
            readonly typeId: 'cipherstash/eql-v3/eql_v3_text@1';
          },
          {
            readonly familyId: 'sql';
            readonly nativeType: 'public.eql_v3_text_eq';
            readonly targetId: 'postgres';
            readonly typeId: 'cipherstash/eql-v3/eql_v3_text_eq@1';
          },
          {
            readonly familyId: 'sql';
            readonly nativeType: 'public.eql_v3_text_match';
            readonly targetId: 'postgres';
            readonly typeId: 'cipherstash/eql-v3/eql_v3_text_match@1';
          },
          {
            readonly familyId: 'sql';
            readonly nativeType: 'public.eql_v3_text_ord_ore';
            readonly targetId: 'postgres';
            readonly typeId: 'cipherstash/eql-v3/eql_v3_text_ord_ore@1';
          },
          {
            readonly familyId: 'sql';
            readonly nativeType: 'public.eql_v3_text_ord';
            readonly targetId: 'postgres';
            readonly typeId: 'cipherstash/eql-v3/eql_v3_text_ord@1';
          },
          {
            readonly familyId: 'sql';
            readonly nativeType: 'public.eql_v3_text_search';
            readonly targetId: 'postgres';
            readonly typeId: 'cipherstash/eql-v3/eql_v3_text_search@1';
          },
          {
            readonly familyId: 'sql';
            readonly nativeType: 'public.eql_v3_boolean';
            readonly targetId: 'postgres';
            readonly typeId: 'cipherstash/eql-v3/eql_v3_boolean@1';
          },
          {
            readonly familyId: 'sql';
            readonly nativeType: 'public.eql_v3_real';
            readonly targetId: 'postgres';
            readonly typeId: 'cipherstash/eql-v3/eql_v3_real@1';
          },
          {
            readonly familyId: 'sql';
            readonly nativeType: 'public.eql_v3_real_eq';
            readonly targetId: 'postgres';
            readonly typeId: 'cipherstash/eql-v3/eql_v3_real_eq@1';
          },
          {
            readonly familyId: 'sql';
            readonly nativeType: 'public.eql_v3_real_ord_ore';
            readonly targetId: 'postgres';
            readonly typeId: 'cipherstash/eql-v3/eql_v3_real_ord_ore@1';
          },
          {
            readonly familyId: 'sql';
            readonly nativeType: 'public.eql_v3_real_ord';
            readonly targetId: 'postgres';
            readonly typeId: 'cipherstash/eql-v3/eql_v3_real_ord@1';
          },
          {
            readonly familyId: 'sql';
            readonly nativeType: 'public.eql_v3_double';
            readonly targetId: 'postgres';
            readonly typeId: 'cipherstash/eql-v3/eql_v3_double@1';
          },
          {
            readonly familyId: 'sql';
            readonly nativeType: 'public.eql_v3_double_eq';
            readonly targetId: 'postgres';
            readonly typeId: 'cipherstash/eql-v3/eql_v3_double_eq@1';
          },
          {
            readonly familyId: 'sql';
            readonly nativeType: 'public.eql_v3_double_ord_ore';
            readonly targetId: 'postgres';
            readonly typeId: 'cipherstash/eql-v3/eql_v3_double_ord_ore@1';
          },
          {
            readonly familyId: 'sql';
            readonly nativeType: 'public.eql_v3_double_ord';
            readonly targetId: 'postgres';
            readonly typeId: 'cipherstash/eql-v3/eql_v3_double_ord@1';
          },
          {
            readonly familyId: 'sql';
            readonly nativeType: 'public.eql_v3_json_search';
            readonly targetId: 'postgres';
            readonly typeId: 'cipherstash/eql-v3/eql_v3_json_search@1';
          },
        ];
      };
      readonly version: '0.0.1';
    };
  };
  readonly meta: {};

  readonly profileHash: ProfileHash;
};

export type Contract = ContractWithTypeMaps<ContractBase, TypeMaps>;

export type Namespaces = Contract['storage']['namespaces'];
